## 1.4.1 넘파이
### 빠르고 효율적인 계산을 위해 만들어진 파이썬 라이브러리
### 고성능의 다차원 배열 객체와 이러한 배열을 계산할 효율적인 도구를 제공

### 넘파이 배열

In [1]:
# numpy 불러오기
import numpy as np

In [2]:
# 임의의 2차원 배열 생성
a = np.array([[1,2,3], [1,5,9], [3,5,7]])

# 배열의 축(차원)의 수를 반환
print(a.ndim)  
# 2 

# 배열의 형태를 반환
print(a.shape) 
# (3,3)

# 배열 내 원소의 총 개수를 반환
print(a.size) 
# 9

# 배열 내 원소들의 자료형을 반환
print(a.dtype) 
# dtype('int32')

2
(3, 3)
9
int32


In [3]:
#원소가 모두 0인 배열 생성
a = np.zeros((2,3))
print(a)      
# array([[0., 0., 0.],
#        [0., 0., 0.]])

#원소가 모두 1인 배열 생성
b = np.ones((2,1)) 
print(b)      
# array([[1.],
#        [1.]])

#배열의 크기만 정해주고 원소값을 초기화하지 않은 배열 생성
c = np.empty((2,2)) 
print(c)      
# array([[1.96088859e+243, 5.22864540e-067],
#        [1.47173270e-052, 1.47214053e-052]])

# 파이썬의 range함수와 유사한 형태로 배열 생성, 배열의 원소들이 수열을 구성
# 10부터 30전 까지 5단위로 배열 생성
d = np.arange(10, 30, 5) 
print(d)      
# array([10, 15, 20, 25])

# 배열의 모든 값이 하나의 상수인 배열 생성
#원소가 모두 4인 배열 생성
e = np.full((2, 2), 4)
print(e)      
# array([[4, 4],
#        [4, 4]])

# 지정한 크기의 단위행렬 생성
# 3x3 크기의 단위행렬 생성
f = np.eye(3) 
print(f)      
# array([[1., 0., 0.],
#        [0., 1., 0.]
#        [0., 0., 1.]))

# 임의값을 가지는 배열 생성
g = np.random.random((2, 2)) 
print(g)      
# array([[0.94039485, 0.18284953],
#        [0.59283818, 0.48592838]])

[[0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]]
[[6.23040373e-307 1.11261434e-306]
 [6.23055651e-307 1.69120688e-306]]
[10 15 20 25]
[[4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.92503201 0.30428946]
 [0.59491522 0.98109109]]


### 넘파이 기본연산

In [4]:
# 임의의 1차원 넘파이 배열 생성
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# 배열의 합
print(a+b)                     
# array([11, 22, 33])

# 배열의 합
print(np.add(a,b)) # 위의 연산과 같다.        
# array([11, 22, 33]) 

# 배열의 차
print(b-a)                      
# array([9, 18, 27])

# 배열의 차
print(np.subtract(b,a)) # 위의 연산과 같다.
# array([9, 18, 27])

# 배열 제곱 연산
print(a**2)                   
# array([1, 4, 9])

# 배열의 원소가 지정한 조건에 맞는지
print(b<15)                   
# array([True, False, False])


# 임의의 2차원 넘파이 배열 생성
C = np.array([[1, 2],
              [3, 4]])
D = np.array([[10, 20],
              [30, 10]])
# 원소별 곱셈
print(C*D)  
# array([[10, 40],
#        [90, 40]])

# 내적(dot product) 계산
print(np.dot(C,D)) 
# array([[ 70,  40],
#        [150, 100]])

#내적의 또 다른 사용법
print(C.dot(D)) 
# array([[ 70,  40],
#        [150, 100]])

[11 22 33]
[11 22 33]
[ 9 18 27]
[ 9 18 27]
[1 4 9]
[ True False False]
[[10 40]
 [90 40]]
[[ 70  40]
 [150 100]]
[[ 70  40]
 [150 100]]


In [5]:
# 임의의 2차원 배열 생성
a = np.array([[ 1, 2, 3, 4],
              [ 5, 6, 7, 8],
              [ 1, 3, 5, 7]])

# 0축, 즉 열을 기준으로한 덧셈
print(a.sum(axis=0)) 
# array([7, 11, 15, 19])

# 1축, 즉 행을 기준으로한 덧셈
print(a.sum(axis=1)) 
# array([10, 26, 16])

# 각 행에서의 최대값
print(a.max(axis=1)) 
# array([4, 8, 7])

[ 7 11 15 19]
[10 26 16]
[4 8 7]


### 넘파이 배열 인덱싱, 슬라이싱

In [ ]:
# 임의의 배열 생성
a = np.array([1, 2, 3, 4, 5, 6, 7])

# 4번째 원소 값
print(a[3]) 
# 4

# 마지막 원소 값
print(a[-1]) 
# 7

# 3번째 원소부터 5번째 원소까지
print(a[2: 5]) 
# array([3, 4, 5])

# 3번째 원소부터 끝까지
print(a[2: ])
# array([3, 4, 5, 6, 7])

# 4번째 원소까지
print(a[ :4])
# array([1, 2, 3, 4])

In [ ]:
# 임의의 2차원 배열 생성
a = np.array([[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9]])

# 2행 3열의 원소 값
print(a[1, 2])
# 6

# 2열의 모든 원소
print(a[ : , 1]) 
# array([2, 5, 8])

# 마지막 행
print(a[-1]) 
# array([7, 8, 9])

### 넘파이 배열 형태 변환

In [ ]:
# 임의의 2차원 배열 생성
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

# 1차원 배열(벡터)로 만들어준다.
print(a.ravel()) 
# array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# 배열의 형태를 바꾼다.
# 2행 6열짜리 배열로 만든다.
print(a.reshape(2, 6))
# array([[  1,  2,  3,  4,  5,  6],
#        [  7,  8,  9, 10, 11, 12]])


# 배열을 transpose한다.
print(a.T)
# array([[  1,  5,  9],
#        [  2,  6, 10],
#        [  3,  7, 11],
#        [  4,  8, 12]])

In [ ]:
# 3행만 지정해주고 열에 -1을 넣으면 자동으로 3행짜리 배열로 reshape한다.
print(a.reshape(3, -1)) 
# array([[  1,  2,  3,  4],
#        [  5,  6,  7,  8],
#        [  9, 10, 11, 12]]) 

### 넘파이 브로드캐스팅

In [ ]:
# 브로드 캐스팅을 사용하지 않는 경우

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])
y = np.empty_like(a) # 배열 a와 크기가 같은 원소가 비어있는 배열 생성

# 배열 b를 a의 각 행에 더해주기 위해 반복문을 사용한다.
for i in range(3):
    y[i, : ] = a[i, : ] + b


print(y)
# array([[  2,  2,  4],
#        [  5,  5,  7],
#        [  8,  8, 10]])

In [ ]:
# 브로드 캐스팅을 사용하는 경우

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,0,1])

c = a + b # c를 따로 선언 할 필요 없이 만들 수 있다.
print(c)
# array([[  2,  2,  4],
#        [  5,  5,  7],
#        [  8,  8, 10]])